package com.sachin.URLshortener.Service;


import com.sachin.URLshortener.Model.UrlEntity;
import com.sachin.URLshortener.Repository.UrlRepository;
import org.apache.commons.validator.routines.UrlValidator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

@Service
public class UrlService {
    @Autowired
    private UrlRepository urlRepository;

    // SCENARIO 1: User wants to shorten a URL
    public String shortenUrl(String originalUrl) {

        // 1. Validate the URL format
        UrlValidator validator = new UrlValidator(new String[]{"http", "https"});

        if (!validator.isValid(originalUrl)) {
            throw new ResponseStatusException(
                    HttpStatus.BAD_REQUEST, "Invalid URL format. Make sure it starts with http:// or https://"
            );
        }
        // 2. Save the long URL to the DB first.
        // We do this to get the unique 'ID' generated by the database.
        UrlEntity url = new UrlEntity();
        url.setLongUrl(originalUrl);

        UrlEntity savedUrl = urlRepository.save(url);
        // Save and get the object back (now with ID)

        // 3. Convert the new unique ID into a short string
        return Base62Converter.encode(savedUrl.getId());
    }

    // SCENARIO 2: User clicks a short link
    public String getOriginalUrl(String shortCode) {
        // 1. Convert the short code (e.g., "g8") back to an ID (e.g., 1000)
        long id = Base62Converter.decode(shortCode);

        // 2. Find the database row with that ID
        UrlEntity entity = urlRepository.findById(id)
                .orElseThrow(() -> new ResponseStatusException(
                        HttpStatus.NOT_FOUND, "Short URL not found: " + shortCode
                ));
        // 1. Increment the count in memory
        entity.setClickCount(entity.getClickCount() + 1);

        // 2. CRITICAL: Save it back to the database!
        urlRepository.save(entity);  // <--- ARE YOU MISSING THIS LINE?

        return entity.getLongUrl();
    }
    public long getClickCount(String shortCode) {
        long id = Base62Converter.decode(shortCode);
        UrlEntity entity = urlRepository.findById(id)
                .orElseThrow(() -> new ResponseStatusException(
                        HttpStatus.NOT_FOUND, "Short URL not found"
                ));
        return entity.getClickCount();
    }
}
